# Generated by Django 6.0.3 on 2026-05-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_order_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Optional image URL for the product'),
        ),
    ]
